###########################################
# makefile for shell program
###########################################
# this file was generated by ai (chatgpt)
# to use with other C projects change
# EXECUTABLE= and SOURCE=
###########################################
CC=gcc
CFLAGS=-c -Wall -lpthread #-Wall = all, warnings -c = ???, "-g -O0" is for debug
LDFLAGS=
SOURCES=linecount.c
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=linecount.bin

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)
